name: mobile
description: A simple mobile app for tracking activities.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.2.1+20230814
publish_to: none

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  adair_flutter_lib:
    # ignore: invalid_dependency
    path: ../../adair-flutter-lib

  community_charts_flutter: ^1.0.4            # https://pub.dev/packages/community_charts_flutter
  collection: ^1.19.1                         # https://pub.dev/packages/collection (Dart)
  device_info_plus: ^11.3.0                   # https://pub.dev/packages/device_info_plus (Flutter)
  share_plus: ^10.1.4                         # https://pub.dev/packages/share_plus (Verified)
  file_picker: ^10.0.0                        # https://pub.dev/packages/file_picker (Verified)
  fixnum: ^1.1.1                              # https://pub.dev/packages/fixnum (Dart)
  flutter_email_sender: ^7.0.0                # https://pub.dev/packages/flutter_email_sender
  http: ^1.3.0                                # https://pub.dev/packages/http (Dart)
  intl: ^0.20.2                               # https://pub.dev/packages/intl
  live_activities: ^2.4.3                     # https://pub.dev/packages/live_activities
  package_info_plus: ^8.2.1                   # https://pub.dev/packages/package_info_plus
  path: ^1.9.1                                # https://pub.dev/packages/path (Dart)
  path_provider: ^2.1.5                       # https://pub.dev/packages/path_provider
  quiver: ^3.2.2                              # https://pub.dev/packages/quiver
  shared_preferences: ^2.5.3                  # https://pub.dev/packages/shared_preferences
  shared_preference_app_group: ^1.1.1         # https://pub.dev/packages/shared_preference_app_group
  shared_preferences_android: ^2.4.15         # https://pub.dev/packages/shared_preferences_android
  sqflite: ^2.4.2                             # https://pub.dev/packages/sqflite
  url_launcher: ^6.3.1                        # https://pub.dev/packages/url_launcher
  uuid: ^4.5.1                                # https://pub.dev/packages/uuid
  firebase_crashlytics: ^4.3.3                # https://pub.dev/packages/firebase_crashlytics
  firebase_core: ^3.12.0                      # https://pub.dev/packages/firebase_core
  firebase_analytics: ^11.4.3                 # https://pub.dev/packages/firebase_analytics
  timezone: ^0.10.0                           # https://pub.dev/packages/timezone
  wakelock_plus: ^1.3.2                       # https://pub.dev/packages/wakelock_plus

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15             # https://pub.dev/packages/build_runner (Dart)
  mockito: ^5.4.5                   # https://pub.dev/packages/mockito (Dart)
  flutter_lints: ^5.0.0             # https://pub.dev/packages/flutter_lints (Flutter)

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/feedback_template
    - assets/sensitive.properties

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: CustomIcons
      fonts:
        - asset: fonts/CustomIcons.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
